title: Standard Bayesian Knowledge Tracing Models
description: command-line utility for fitting standard BKT models at scale
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
